#!/sbin/runscript

NCD_PIDFILE="/var/run/${SVCNAME}.pid"
NCD_NAME=${NCD_NAME:-"Network Configuration Daemon"}
NCD_SYSLOG_IDENT=${NCD_SYSLOG_IDENT:-"ncd"}
NCD_EXEC=${NCD_EXEC:-"/usr/bin/badvpn-ncd"}

depend() {
    need net
    after bootmisc
    before netmount
}

start() {
    ebegin "Starting ${NCD_NAME}"
    local args=( "${NCD_ARGS[@]}" --config-file "${NCD_CONFIG}" )
    if [ "$NCD_SYSLOG_IDENT" != "none" ]; then
        args=( "${args[@]}" --logger syslog --syslog-ident "$NCD_SYSLOG_IDENT" )
    fi
    start-stop-daemon --start --pidfile "${NCD_PIDFILE}" --background --make-pidfile --exec "${NCD_EXEC}" -- "${args[@]}"
    eend $? "Failed to start ${NCD_NAME}"
}

stop() {
    ebegin "Stopping ${NCD_NAME}"
    start-stop-daemon --stop --pidfile "${NCD_PIDFILE}"
    eend $? "Failed to stop ${NCD_NAME}"
}
