#!/sbin/runscript

VPN_PIDFILE="/var/run/${SVCNAME}.pid"
VPN_NAME=${VPN_NAME:-"BadVPN server"}
VPN_SYSLOG_IDENT=${VPN_SYSLOG_IDENT:-"badvpn-server"}
VPN_EXEC=${VPN_EXEC:-"/usr/bin/badvpn-server"}

depend() {
	need net
}

start() {
	ebegin "Starting $VPN_NAME"
        local args=("${VPN_ARGS[@]}")
        if [ "$VPN_SYSLOG_IDENT" != "none" ]; then
                args=("${args[@]}" --logger syslog --syslog-ident "$VPN_SYSLOG_IDENT")
        fi
	start-stop-daemon --start --pidfile $VPN_PIDFILE --background --make-pidfile --user $VPN_USER --exec $VPN_EXEC -- "${args[@]}"
	eend $? "Failed to start $VPN_NAME"
}

stop() {
	ebegin "Stopping $VPN_NAME"
	start-stop-daemon --stop --pidfile $VPN_PIDFILE
	eend $? "Failed to stop $VPN_NAME"
}
