#!/sbin/runscript
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: 

PIDFILE=/var/run/${SVCNAME}.pid

depend() {
	use net.*
}

start() {
	ebegin "Starting imspector"
	start-stop-daemon --start --quiet --chuid $USER --pidfile "${PIDFILE}" --exec /usr/sbin/imspector --  $RUN_OPTIONS
	eend $?
}

stop() {
	ebegin "Stopping imspector"
	start-stop-daemon --stop --quiet --pidfile "${PIDFILE}" --exec /usr/sbin/imspector
	eend $?
}
