# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="5"

MODULE_AUTHOR="SIXTEASE"


inherit perl-module

DESCRIPTION="Mapping of XML entities to Unicode"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

S=${WORKDIR}/${PN}
DEPEND="dev-lang/perl virtual/perl-Module-Build"
