#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/www-servers/nginx/files/nginx.init-r2,v 1.1 2010/01/03 19:51:41 djc Exp $

APPSPATH=/var/lib/syncthing
PROGNAME=syncthing
PIDPATH=/var/run/${PROGNAME}
PIDFILE=${PIDPATH}/${PROGNAME}.pid
LOGPATH=/var/log/${PROGNAME}

depend() {
	need net
	use dns logger localmount
}

start() {
	if [ ! -d $PIDPATH ] ; then
		mkdir -p $PIDPATH
		chown $USER $PIDPATH
	fi
	if [ ! -d $LOGPATH ] ; then
		mkdir -p $LOGPATH
		chown $USER $LOGPATH
	fi
	if [ -z ${USER} ]; then 
		echo USER is not set in /etc/conf.d/syncthing - edit that variable to the name of an existing user and try again
		return 1
	fi
	if [ -f $PIDFILE ]; then
		chown $USER $PIDFILE
	fi
	if [ -f $LOGPATH ]; then
		chown -R $LOGPATH/* $USER
	fi

	ebegin "Starting $PROGNAME"
	start-stop-daemon --start --pidfile $PIDFILE \
		--user $USER \
		--background -1 $LOGPATH/$PROGNAME.log -2 $LOGPATH/$PROGNAME.err \
		--ionice 1 --make-pidfile \
		--exec /usr/bin/syncthing -- -no-browser $SYNCTHING_OPTS
	eend $? "Failed to start $PROGNAME"
}

stop() {
	ebegin "Stopping $PROGNAME"
	start-stop-daemon --stop --pidfile $PIDFILE
	eend $? "Failed to stop $PROGNAME"
	rm -f /var/run/$PIDFILE
}

